baseURL = "https://fretcandy.com/"
languageCode = "en-us"
title = "FretCandy"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "FretCandy - All rights reserved"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="Sweet sounds made simple."
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "FretCandy"
  thumbnail = "/images/logo.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/logo.png"
  title = "FretCandy"
  subtitle = "Sweet sounds made simple."
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Tools"
    weight = 100
    identifier = "tools"
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/"
